// legacy-stencil-components/menu/templates/components.tsx
import { h } from '@stencil/core';

export default () => <docs-nav items={items}/>;

const items = {
  'menu-api-action-sheet': {
    'ion-action-sheet': '/docs/api/action-sheet'
  },
  'menu-api-alert': {
    'ion-alert': '/docs/api/alert'
  },
  'menu-api-badge': {
    'ion-badge': '/docs/api/badge'
  },
  'menu-api-button': {
    'ion-button': '/docs/api/button',
    'ion-ripple-effect': '/docs/api/ripple-effect'
  },
  'menu-api-card': {
    'ion-card': '/docs/api/card',
    'ion-card-content': '/docs/api/card-content',
    'ion-card-header': '/docs/api/card-header',
    'ion-card-subtitle': '/docs/api/card-subtitle',
    'ion-card-title': '/docs/api/card-title'
  },
  'menu-api-checkbox': {
    'ion-checkbox': '/docs/api/checkbox'
  },
  'menu-api-chip': {
    'ion-chip': '/docs/api/chip'
  },
  'menu-api-content': {
    'ion-app': '/docs/api/app',
    'ion-content': '/docs/api/content',
  },
  'menu-api-datetime': {
    'ion-datetime': '/docs/api/datetime',
    'ion-picker': '/docs/api/picker'
  },
  'menu-api-fab': {
    'ion-fab': '/docs/api/fab',
    'ion-fab-button': '/docs/api/fab-button',
    'ion-fab-list': '/docs/api/fab-list'
  },
  'menu-api-grid': {
    'ion-grid': '/docs/api/grid',
    'ion-col': '/docs/api/col',
    'ion-row': '/docs/api/row'
  },
  'menu-api-infinite-scroll': {
    'ion-infinite-scroll': '/docs/api/infinite-scroll',
    'ion-infinite-scroll-content': '/docs/api/infinite-scroll-content'
  },
  'menu-api-icons': {
    'ion-icon': 'https://ionic.io/ionicons'
  },
  'menu-api-input': {
    'ion-input': '/docs/api/input',
    'ion-textarea': '/docs/api/textarea'
  },
  'menu-api-item': {
    'ion-item': '/docs/api/item',
    'ion-item-divider': '/docs/api/item-divider',
    'ion-item-group': '/docs/api/item-group',
    'ion-item-sliding': '/docs/api/item-sliding',
    'ion-item-options': '/docs/api/item-options',
    'ion-item-option': '/docs/api/item-option',
    'ion-label': '/docs/api/label',
    'ion-note': '/docs/api/note'
  },
  'menu-api-list': {
    'ion-list': '/docs/api/list',
    'ion-list-header': '/docs/api/list-header',
    'ion-virtual-scroll': '/docs/api/virtual-scroll'
  },
  'menu-api-media': {
    'ion-avatar': '/docs/api/avatar',
    'ion-icon': 'https://ionic.io/ionicons',
    'ion-img': '/docs/api/img',
    'ion-thumbnail': '/docs/api/thumbnail'
  },
  'menu-api-menu': {
    'ion-menu': '/docs/api/menu',
    'ion-menu-button': '/docs/api/menu-button',
    'ion-menu-toggle': '/docs/api/menu-toggle',
    'ion-split-pane': '/docs/api/split-pane'
  },
  'menu-api-modal': {
    'ion-modal': '/docs/api/modal',
    'ion-backdrop': '/docs/api/backdrop'
  },
  'menu-api-nav': {
    'ion-nav': '/docs/api/nav',
    'ion-nav-link': '/docs/api/nav-link'
  },
  'menu-api-popover': {
    'ion-popover': '/docs/api/popover',
  },
  'menu-api-progress-indicators': {
    'ion-loading': '/docs/api/loading',
    'ion-progress-bar': '/docs/api/progress-bar',
    'ion-skeleton-text': '/docs/api/skeleton-text',
    'ion-spinner': '/docs/api/spinner'
  },
  'menu-api-radio': {
    'ion-radio': '/docs/api/radio',
    'ion-radio-group': '/docs/api/radio-group'
  },
  'menu-api-range': {
    'ion-range': '/docs/api/range'
  },
  'menu-api-refresher': {
    'ion-refresher': '/docs/api/refresher',
    'ion-refresher-content': '/docs/api/refresher-content'
  },
  'menu-api-reorder': {
    'ion-reorder': '/docs/api/reorder',
    'ion-reorder-group': '/docs/api/reorder-group'
  },
  'menu-api-router': {
    'ion-router': '/docs/api/router',
    'ion-router-link': '/docs/api/router-link',
    'ion-router-outlet': '/docs/api/router-outlet',
    'ion-route': '/docs/api/route',
    'ion-route-redirect': '/docs/api/route-redirect'
  },
  'menu-api-searchbar': {
    'ion-searchbar': '/docs/api/searchbar'
  },
  'menu-api-segment': {
    'ion-segment': '/docs/api/segment',
    'ion-segment-button': '/docs/api/segment-button'
  },
  'menu-api-select': {
    'ion-select': '/docs/api/select',
    'ion-select-option': '/docs/api/select-option'
  },
  'menu-api-slides': {
    'ion-slides': '/docs/api/slides',
    'ion-slide': '/docs/api/slide'
  },
  'menu-api-tabs': {
    'ion-tabs': '/docs/api/tabs',
    'ion-tab': '/docs/api/tab',
    'ion-tab-bar': '/docs/api/tab-bar',
    'ion-tab-button': '/docs/api/tab-button'
  },
  'menu-api-toast': {
    'ion-toast': '/docs/api/toast',
  },
  'menu-api-toggle': {
    'ion-toggle': '/docs/api/toggle'
  },
  'menu-api-toolbar': {
    'ion-toolbar': '/docs/api/toolbar',
    'ion-header': '/docs/api/header',
    'ion-footer': '/docs/api/footer',
    'ion-title': '/docs/api/title',
    'ion-buttons': '/docs/api/buttons',
    'ion-back-button': '/docs/api/back-button'
  },
  'menu-api-typography': {
    'ion-text': '/docs/api/text'
  },
  'menu-api-resources': {
    'menu-api-index': '/docs/api'
  }
};

// src/components/menu/templates/components.tsx
export default () => <docs-nav items={items}/>;

const items = {
  'Action Sheet': {
    'ion-action-sheet': '/docs/api/action-sheet',
    'ion-action-sheet-controller': '/docs/api/action-sheet-controller'
  },
  'Alert': {
    'ion-alert': '/docs/api/alert',
    'ion-alert-controller': '/docs/api/alert-controller'
  },
  'Badge': {
    'ion-badge': '/docs/api/badge'
  },
  'Button': {
    'ion-button': '/docs/api/button',
    'ion-ripple-effect': '/docs/api/ripple-effect'
  },
  'Card': {
    'ion-card': '/docs/api/card',
    'ion-card-content': '/docs/api/card-content',
    'ion-card-header': '/docs/api/card-header',
    'ion-card-subtitle': '/docs/api/card-subtitle',
    'ion-card-title': '/docs/api/card-title'
  },
  'Checkbox': {
    'ion-checkbox': '/docs/api/checkbox'
  },
  'Chip': {
    'ion-chip': '/docs/api/chip'
  },
  'Content': {
    'ion-app': '/docs/api/app',
    'ion-content': '/docs/api/content',
  },
  'Date & Time Pickers': {
    'ion-datetime': '/docs/api/datetime',
    'ion-picker': '/docs/api/picker',
    'ion-picker-controller': '/docs/api/picker-controller'
  },
  'Floating Action Button': {
    'ion-fab': '/docs/api/fab',
    'ion-fab-button': '/docs/api/fab-button',
    'ion-fab-list': '/docs/api/fab-list'
  },
  'Grid': {
    'ion-grid': '/docs/api/grid',
    'ion-col': '/docs/api/col',
    'ion-row': '/docs/api/row'
  },
  'Infinite Scroll': {
    'ion-infinite-scroll': '/docs/api/infinite-scroll',
    'ion-infinite-scroll-content': '/docs/api/infinite-scroll-content'
  },
  'Icons': {
    'ion-icon': 'https://ionicons.com'
  },
  'Input': {
    'ion-input': '/docs/api/input',
    'ion-textarea': '/docs/api/textarea'
  },
  'Item': {
    'ion-item': '/docs/api/item',
    'ion-item-divider': '/docs/api/item-divider',
    'ion-item-group': '/docs/api/item-group',
    'ion-item-sliding': '/docs/api/item-sliding',
    'ion-item-options': '/docs/api/item-options',
    'ion-item-option': '/docs/api/item-option',
    'ion-label': '/docs/api/label',
    'ion-note': '/docs/api/note'
  },
  'List': {
    'ion-list': '/docs/api/list',
    'ion-list-header': '/docs/api/list-header',
    'ion-virtual-scroll': '/docs/api/virtual-scroll'
  },
  'Media': {
    'ion-avatar': '/docs/api/avatar',
    'ion-icon': 'https://ionicons.com',
    'ion-img': '/docs/api/img',
    'ion-thumbnail': '/docs/api/thumbnail'
  },
  'Menu': {
    'ion-menu': '/docs/api/menu',
    'ion-menu-button': '/docs/api/menu-button',
    'ion-menu-controller': '/docs/api/menu-controller',
    'ion-menu-toggle': '/docs/api/menu-toggle',
    'ion-split-pane': '/docs/api/split-pane'
  },
  'Modal': {
    'ion-modal': '/docs/api/modal',
    'ion-modal-controller': '/docs/api/modal-controller',
    'ion-backdrop': '/docs/api/backdrop'
  },
  'Navigation': {
    'ion-nav': '/docs/api/nav',
    'ion-nav-pop': '/docs/api/nav-pop',
    'ion-nav-push': '/docs/api/nav-push',
    'ion-nav-set-root': '/docs/api/nav-set-root'
  },
  'Popover': {
    'ion-popover': '/docs/api/popover',
    'ion-popover-controller': '/docs/api/popover-controller'
  },
  'Progress Indicators': {
    'ion-loading': '/docs/api/loading',
    'ion-loading-controller': '/docs/api/loading-controller',
    'ion-progress-bar': '/docs/api/progress-bar',
    'ion-skeleton-text': '/docs/api/skeleton-text',
    'ion-spinner': '/docs/api/spinner'
  },
  'Radio': {
    'ion-radio': '/docs/api/radio',
    'ion-radio-group': '/docs/api/radio-group'
  },
  'Range': {
    'ion-range': '/docs/api/range'
  },
  'Refresher': {
    'ion-refresher': '/docs/api/refresher',
    'ion-refresher-content': '/docs/api/refresher-content'
  },
  'Reorder': {
    'ion-reorder': '/docs/api/reorder',
    'ion-reorder-group': '/docs/api/reorder-group'
  },
  'Routing': {
    'ion-router': '/docs/api/router',
    'ion-router-outlet': '/docs/api/router-outlet',
    'ion-route': '/docs/api/route',
    'ion-route-redirect': '/docs/api/route-redirect'
  },
  'Searchbar': {
    'ion-searchbar': '/docs/api/searchbar'
  },
  'Segment': {
    'ion-segment': '/docs/api/segment',
    'ion-segment-button': '/docs/api/segment-button'
  },
  'Select': {
    'ion-select': '/docs/api/select',
    'ion-select-option': '/docs/api/select-option'
  },
  'Slides': {
    'ion-slides': '/docs/api/slides',
    'ion-slide': '/docs/api/slide'
  },
  'Tabs': {
    'ion-tabs': '/docs/api/tabs',
    'ion-tab': '/docs/api/tab',
    'ion-tab-bar': '/docs/api/tab-bar',
    'ion-tab-button': '/docs/api/tab-button'
  },
  'Toast': {
    'ion-toast': '/docs/api/toast',
    'ion-toast-controller': '/docs/api/toast-controller'
  },
  'Toggle': {
    'ion-toggle': '/docs/api/toggle'
  },
  'Toolbar': {
    'ion-toolbar': '/docs/api/toolbar',
    'ion-header': '/docs/api/header',
    'ion-footer': '/docs/api/footer',
    'ion-title': '/docs/api/title',
    'ion-buttons': '/docs/api/buttons',
    'ion-back-button': '/docs/api/back-button'
  },
  'Typography': {
    'ion-anchor': '/docs/api/anchor',
    'ion-text': '/docs/api/text'
  },
  'Resources': {
    'API Index': '/docs/api'
  }
};
