// src/components/menu/templates/cli.tsx
import commands from '../data/cli-commands.json';

export default () => <docs-nav items={items}/>;

const items = {
  'CLI Documentation': {
    'Overview': '/docs/cli',
    'Configuration': '/docs/cli/configuration',
    'Using a Proxy': '/docs/cli/using-a-proxy',
    'Change Log': 'https://github.com/ionic-team/ionic-cli/blob/master/packages/ionic/CHANGELOG.md'
  },
  'Command Reference': Object.entries(commands).sort()
};

// src/components/legacy-stencil-components/menu/templates/cli.tsx
import { h } from '@stencil/core';

import commands from '../data/cli-commands.json';

export default () => <docs-nav items={items}/>;

const items = {
  'menu-cli': {
    'menu-cli-overview': '/docs/cli',
    'menu-cli-configuration': '/docs/cli/configuration',
    'menu-cli-livereload': '/docs/cli/livereload',
    'menu-cli-using-a-proxy': '/docs/cli/using-a-proxy',
    'menu-cli-changelog': 'https://github.com/ionic-team/ionic-cli/blob/develop/packages/@ionic/cli/CHANGELOG.md'
  },
  'menu-cli-commands': Object.entries(commands).sort()
};
