// src/components/menu/templates/native.tsx
import plugins from '../data/native-plugins.json';

export default () => <docs-nav items={items}/>;

const items = {
  'Enterprise': {
    'Native Core': '/docs/native/native-core',
    'Active Directory': 'https://ionicframework.com/integrations/ms-activedirectory-ms-adal',
    'Identity Vault': '/docs/native/identity-vault',
    'mParticle': '/docs/native/mparticle',
    'Offline Support': 'https://ionicframework.com/integrations/couchbase-lite'
  },
  'Plugins': Object.entries(plugins).sort()
};

// src/components/legacy-stencil-components/menu/templates/native.tsx
import { Component, h } from '@stencil/core';

import { l10n } from '../../../l10n';
import communityPlugins from '../data/native-plugins.json';

@Component({
  tag: 'docs-menu-native',
  styleUrl: 'native.css'
})
export class DocsMenuNative {

  render() {
    return [
      <docs-menu-collapsible heading={l10n.getString('menu-native-getting-started')}>
        <docs-nav items={this.gettingStarted} />
      </docs-menu-collapsible>,

      <docs-menu-collapsible heading={l10n.getString('menu-native-plugins')}>
          <docs-nav items={this.communityPlugins} />
      </docs-menu-collapsible>
    ];
  }

  gettingStarted = {
    '': {
      'menu-native-home': '/docs/native',
      'menu-native-community': '/docs/native/community',
      'menu-native-faq': '/docs/native/faq',
      'menu-native-community-v-premier': 'https://ionic.io/docs/premier-plugins'
    }
  };

  communityPlugins = {
    '': Object.entries(communityPlugins).sort()
  };
}
